import {Media} from "./Media";

export interface Content {
  contentType: 'episode' | 'movie';
  addedAt: string,
  key: string,
  lastViewedAt: string,
  librarySectionID: string,
  summary: string,
  thumbUrl: string,
  title: string,
  titleSort: string,
  type: number,
  updatedAt: string,
  viewCount: number,
  duration: number,
  guid: string,
  originalTitle: string,
  originallyAvailableAt: string,
  rating: number,
  ratingImage: string,
  studio: string,
  tagline: string,
  userRating: number,
  year: number,
  seasonNumber?: string,
  seasonEpisode?: string,
  seriesTitle?: string,
  media: Media[],
  library: string,
  url: string,
  ignored: boolean,
}
